/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.


const isLocalhost = Boolean(
  window.location.hostname === "localhost" ||
    // [::1] is the IPv6 localhost address.
    window.location.hostname === "[::1]" ||
    // 127.0.0.1/8 is considered localhost for IPv4.
    window.location.hostname.match(
      /^127(?:\.(?:25[0-5]|2[0-4][0-9]|[01]?[0-9][0-9]?)){3}$/
    )
);


const awsmobile = {
  "aws_project_region": "sa-east-1",
  "aws_appsync_graphqlEndpoint": "https://d46kainwkve7vddoq5siczvgeu.appsync-api.sa-east-1.amazonaws.com/graphql",
  "aws_appsync_region": "sa-east-1",
  "aws_appsync_authenticationType": "API_KEY",
  "aws_appsync_apiKey": "da2-q5s2d67szbhgxhrsj3hyaj5yaa",
  "aws_cognito_identity_pool_id": "sa-east-1:f3c8b2e1-2fcf-4e5a-973f-e66b148a3534",
  "aws_cognito_region": "sa-east-1",
  "aws_user_pools_id": "sa-east-1_ZzovTcK3c",
  "aws_user_pools_web_client_id": "5upvkfapuo0bi3sru3f1d9g0dh",
  "oauth": {},
  "aws_cognito_username_attributes": [],
  "aws_cognito_social_providers": [],
  "aws_cognito_signup_attributes": [
      "EMAIL"
  ],
  "aws_cognito_mfa_configuration": "OFF",
  "aws_cognito_mfa_types": [
      "SMS"
  ],
  "aws_cognito_password_protection_settings": {
      "passwordPolicyMinLength": 8,
      "passwordPolicyCharacters": []
  },
  "aws_cognito_verification_mechanisms": [
      "EMAIL"
  ]
};


export default awsmobile;
